services:
  - type: web
    name: esmart-api-gateway
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: EXPRESS_API_URL
        sync: false
      - key: PYTHON_API_URL
        sync: false
