services:
  - type: web
    name: esmart-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
    autoDeploy: true

databases:
  - name: esmart-postgres
    type: postgres
    plan: free
    ipAllowList: []
